fixup case of backedge from header to header
numba/numba-rvsdg pull request #52
Opened 2023-04-26 14:10 UTC by esc

Fixes #45

Headers of multi-block loops that have a backedge to themselves, didn't have this processed.

The case of:

`label not in doms[jt]`

accounts for the case, where there were multiple entry edges into the loop and the original header has been replaced with a synthetic one.

An alternative fix would have been to simply delete this check, but then this breaks the test case `test_double_header` (after hacking the followup issues). This fix is non-intrusive and a test for the edge cases has been added too.

2023-05-04 11:22 UTC, kc611 requested changes
This LGTM and also has a test present.

Could you please rebase this onto the current `main`. Thanks.

2023-05-08 16:35 UTC, esc commented
It looks like with the merge of the `remove_labels` PR, the test became stricter and exposed that this test had been working by accident. 08b019eaac56f0c0597af69f38603c680a6897d2 fixes -- basically on input we have `[1, 2]` and the link to `1` is replaced with a link to 5 -- so the expected jump_targets should be `[5, 2]` -- the commit fixes that!

2023-05-25 17:53 UTC, kc611 approved these changes

2023-05-25 17:55 UTC, kc611 commented
The changes LGTM! I think we can go ahead with the merge on this one.

2023-05-29 14:02 UTC, esc commented
@kc611 thank you for the review!

2023-05-29 14:02 UTC, merged