fix missing variable assignment
numba/numba-rvsdg pull request #53
Opened 2023-04-26 14:26 UTC by esc

Fixes #46

The problem was that, in case of a multi-header loop with a single exit, the control-variable wasn't being setup correctly.

A further problem is that, even though this was tested, only the overall block structure of the SCFG was being compared. However the instructions of the blocks themselves were not, so this went unnoticed.

The fix for the test is to add the instructions contained within blocks to the YAML and then we can test this properly.

2023-05-04 10:58 UTC, kc611 requested changes
Might be worth adding the original failure as a test for this.

2023-05-04 10:58 UTC, kc611 commented on numba_rvsdg/core/transformations.py
> +                    if needs_synth_exit or headers_were_unified:
So what this basically means:

If there's no need for a synthetic exit and the headers were unified in a loop restructure, then the variable assignment for exit variable (i.e. the exit variable would be assigned the value) equal to the one that points it to the jump target i.e. the newly created/unified header.

Is the above statement true?

2023-06-13 10:50 UTC, esc commented
> Might be worth adding the original failure as a test for this.

I think this will need an enhancement of the test-suite such that it can be properly tested.

2023-06-13 10:58 UTC, esc commented
> > Might be worth adding the original failure as a test for this.
> 
> I think this will need an enhancement of the test-suite such that it can be properly tested.

Maybe something like: https://github.com/numba/numba-rvsdg/pull/57 could help to test this, but YAML testing would be better.

2023-06-15 13:23 UTC, kc611 approved these changes
Alright, Testing can be done once #57 is merged, rest of it LGTM!

2023-06-22 12:47 UTC, kc611 approved these changes

2023-06-22 12:48 UTC, merged